# Generated by Django 6.0 on 2026-05-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageapi', '0003_comment_history'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='commenthistory',
            new_name='comment_his_page_id_756d82_idx',
            old_name='comment_hi_page_id_7a8b9c_idx',
        ),
        migrations.RenameIndex(
            model_name='commenthistory',
            new_name='comment_his_comment_33819f_idx',
            old_name='comment_hi_comment_1d2e3f_idx',
        ),
        migrations.RenameIndex(
            model_name='commenthistory',
            new_name='comment_his_command_56a22a_idx',
            old_name='comment_hi_command_4g5h6i_idx',
        ),
        migrations.RenameIndex(
            model_name='inboundevent',
            new_name='inbound_eve_status_5da1c9_idx',
            old_name='inbound_ev_status_0a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='inboundevent',
            new_name='inbound_eve_user_id_4cd01b_idx',
            old_name='inbound_ev_user_id_3d4e5f_idx',
        ),
        migrations.AlterField(
            model_name='inboundevent',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('pending_review', 'Pending Review'), ('blacklisted', 'Blacklisted'), ('rate_limited', 'Rate Limited'), ('spam_hidden', 'Spam Hidden'), ('duplicate', 'Duplicate')], default='received', max_length=30),
        ),
    ]
